"""Skew preference operator tests (theorem T8).

Plant a genuinely cyclic (intransitive) preference structure by generating preferences from a known
rank-1 skew operator, then confirm ``PreferenceRankTest`` recovers it: the rank-k skew model predicts
held-out cyclic pairs well above the best transitive (scalar) baseline, which provably cannot express
a cycle, and the recovered effective preference rank matches the planted one.
"""

from __future__ import annotations

import numpy as np

from reward_lens.geometry import PreferenceRankTest


def _planted_cyclic_dataset(seed: int = 0):
    """Activations plus preferences generated by a known rank-1 skew operator (a cyclic tournament).

    ``s(i, j) = phi_i^T A phi_j`` with ``A = u q^T - q u^T`` is the 2-D cross product of the items'
    coordinates in the (u, q) plane, i.e. ``|v_i||v_j| sin(theta_j - theta_i)``: a rotational,
    intransitive tournament (rock-paper-scissors around the circle) no scalar order can reproduce.
    """
    rng = np.random.default_rng(seed)
    n, d = 70, 8
    phi = rng.standard_normal((n, d))

    basis, _ = np.linalg.qr(rng.standard_normal((d, 2)))
    u, q = basis[:, 0], basis[:, 1]
    a_true = np.outer(u, q) - np.outer(q, u)

    pairs = []
    for i in range(n):
        for j in range(i + 1, n):
            s = phi[i] @ a_true @ phi[j]
            if abs(s) < 1e-9:
                continue
            pairs.append((i, j) if s > 0 else (j, i))  # (winner, loser)
    return phi, np.array(pairs, dtype=np.int64), a_true


def test_preference_rank_recovers_planted_cyclic_structure():
    """The rank-1 skew model recovers the planted cycle above the transitive baseline."""
    phi, pairs, _ = _planted_cyclic_dataset(seed=0)
    ev = PreferenceRankTest(phi, pairs, rank_k=1).run(test_frac=0.3, seed=0)
    res = ev.value

    assert str(ev.gauge) == "invariant"
    # The skew model predicts held-out cyclic preferences well; the scalar order cannot.
    assert res.skew_acc > 0.9, f"skew accuracy too low: {res.skew_acc}"
    assert res.transitive_acc < 0.85, f"transitive baseline unexpectedly high: {res.transitive_acc}"
    assert res.cyclic_recovery > 0.1, f"cyclic recovery margin too small: {res.cyclic_recovery}"
    # A rank-1 skew operator has algebraic rank 2 (one cyclic plane).
    assert res.effective_rank_pairs == 1, f"expected 1 cyclic plane, got {res.effective_rank_pairs}"
    assert res.effective_rank == 2


def test_transitive_data_has_no_cyclic_excess():
    """On preferences from a genuine scalar reward, the skew model earns little cyclic excess.

    When the data is a real total order, both models predict it, so ``cyclic_recovery`` is near zero:
    the skew machinery does not manufacture intransitivity that is not there.
    """
    rng = np.random.default_rng(1)
    n, d = 70, 8
    phi = rng.standard_normal((n, d))
    w_true = rng.standard_normal(d)
    r = phi @ w_true
    pairs = []
    for i in range(n):
        for j in range(i + 1, n):
            pairs.append((i, j) if r[i] > r[j] else (j, i))
    pairs = np.array(pairs, dtype=np.int64)

    res = PreferenceRankTest(phi, pairs, rank_k=1).run(test_frac=0.3, seed=0).value
    assert res.transitive_acc > 0.9  # the scalar model nails a transitive order
    assert res.cyclic_recovery < 0.1  # no spurious cyclic excess
