"""Acceptance: H1 rung 0 and H4, the two instruments the rate package was waiting on.

The clause, in three parts:

*`Ad` is computed per step from a record alone; `rate/regime.py`'s `QUASI_STATIC` condition can now
be answered rather than returning `None`; and a transition width is fitted with its fit quality
reported and validated against planted widths.*

Each part is one test below and none of them is satisfied by a number typed into a fixture. The
adiabaticity number comes out of an exponential schedule whose log derivative is a constant the
record carries, so nobody writes `Ad` anywhere; the `QUASI_STATIC` flip is measured twice on one
record, once with the regime reading alone and once with this package's relaxation time handed to
it; and the transition width is fitted to logistics whose 10-to-90 rise was chosen before the fit
ran.

The fourth test is the real subject. A 200-step GRPO trace of a 0.6M-parameter model against a
length grader is a real optimisation trace and contains no reward-hacking transition, so what it
can support is that the mechanics run on real advantages and a real schedule, and that H4 refuses
on every channel it carries rather than reporting the width of the noise. **No lead time is
reported on it**, because there is nothing on that run for a lead to be ahead of.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest

from reward_lens.core.envelope import RegimeCondition
from reward_lens.core.reading import Refusal, RefusalReason
from reward_lens.core.types import Access, AccessMatrix, Component, Phase, Substrate
from reward_lens.measure.base import Context
from reward_lens.measure.rate.adiabaticity import (
    Adiabaticity,
    RelaxationFloors,
    adiabaticity,
    regime_inputs,
    tau_transfer,
)
from reward_lens.measure.rate.regime import measure_regime
from reward_lens.measure.rate.transition import (
    TransitionCriteria,
    TransitionWidth,
    _logistic,
    available_series,
    fit_transition,
    lead_time,
    series_from_run,
)
from tests.test_measure_rate_h1 import annealed_run, ar1

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "grpo_run"
RECORD_ONLY: AccessMatrix = {Component.RECORD: Access.RECORD}
FAST_TAU = RelaxationFloors(n_boot=120)
FAST_FIT = TransitionCriteria(n_boot=60)


def _context() -> Context:
    """RECORD access, no signal, no grader. If either instrument needs more, it will say so."""
    return Context(
        signal=None,
        access=RECORD_ONLY,
        substrate=Substrate.NEURAL_GEN,
        phase=Phase.POST_RUN,
    )


def open_fixture(which: str):
    """The GRPO record, or a skip. It is regenerated by `tools/make_grpo_fixture.py`."""
    from reward_lens.record.reader import open_run

    root = FIXTURES / which
    runs = root / "runs"
    if not runs.is_dir():
        pytest.skip(f"the {which} GRPO fixture is not on disk; run tools/make_grpo_fixture.py")
    run_id = next(p.name for p in runs.iterdir())
    return open_run(root, run_id.replace("run_", "run:"))


# ---------------------------------------------------------------------------
# Clause 1: Ad per step, from a record alone
# ---------------------------------------------------------------------------


def test_ad_is_computed_per_step_from_a_record_and_nothing_else():
    """RECORD access, no signal, no grader call, and one `Ad` per consecutive pair of steps.

    The schedule is exponential at 0.03 per step in log units, so `d log lambda / dt` is exactly
    0.03 at every step and the only estimated factor in the product is the relaxation time. Nobody
    writes an adiabaticity number anywhere in this test: it is the recorded schedule times a fitted
    time.
    """
    run = annealed_run(rate=0.03, means=ar1(0.55, 60, seed=21))
    instrument = Adiabaticity(run, floors=FAST_TAU)

    pre = instrument.preflight(_context())
    assert pre.ok, pre.render()
    assert pre.cost.is_free

    reading = instrument.estimate(_context())
    assert not isinstance(reading, Refusal), getattr(reading, "render", lambda: reading)()
    value = reading.value
    assert len(value.per_step) == 59
    assert [s.to_step for s in value.per_step] == list(range(1, 60))
    assert all(s.rate == pytest.approx(0.03) for s in value.per_step)
    assert all(s.ad == pytest.approx(value.tau.tau * 0.03) for s in value.per_step)
    assert all(s.ad_low <= s.ad <= s.ad_high for s in value.per_step)

    # The declared quantity travels onto the reading, which is what the unit machinery keys on.
    assert reading.quantity == "run.adiabaticity"
    assert reading.baselines["baseline.assume_quasi_static"] == 0.0
    assert reading.baselines["baseline.unit_relaxation"] == pytest.approx(0.03)


# ---------------------------------------------------------------------------
# Clause 2: QUASI_STATIC can be answered
# ---------------------------------------------------------------------------


def test_quasi_static_is_answered_where_the_regime_reading_alone_returns_none():
    """The same record, measured twice. The only thing that changes is the relaxation time.

    The observable is white noise about a level, which is the commonest shape a short training
    series has. Its uncorrected lag-1 coefficient lands at or below zero, the regime reading
    reports no relaxation time from it, and `QUASI_STATIC` comes back `None` with the reason.

    What answers it is the interval rather than the point. The corrected coefficient on this seed is
    still negative, so the relaxation time is exactly zero: a series with no positive memory relaxes
    inside one step. The upper end of the coefficient's interval is positive and below one, so the
    relaxation time has a finite upper bound, `Ad` has one with it, and the condition can be decided
    on the conservative end. The regime reading has no interval to reach for and so has nothing
    to decide on.
    """
    run = annealed_run(rate=0.01, means=ar1(0.0, 60, seed=13))

    alone = measure_regime(run).conditions[RegimeCondition.QUASI_STATIC]
    assert alone.holds is None, "the regime reading alone is expected to decline on this series"
    assert math.isnan(alone.statistic)
    assert "at or below zero" in alone.detail

    reading = adiabaticity(run, floors=FAST_TAU)
    assert not isinstance(reading, Refusal)
    assert reading.tau.phi_ols <= 0, "the estimator the regime reading uses declines here"
    assert reading.tau.phi > reading.tau.phi_ols, "the correction moves it up"
    assert 0.0 < reading.tau.phi_ci[1] < 1.0
    assert math.isfinite(reading.tau.tau_high) and reading.tau.tau_high > 0.0

    answered = measure_regime(run, inputs=regime_inputs(reading)).conditions[
        RegimeCondition.QUASI_STATIC
    ]
    assert answered.holds is not None, "the condition is answered rather than undetermined"
    assert math.isfinite(answered.statistic)
    assert answered.statistic == pytest.approx(reading.tau.tau_high * 0.01)
    assert answered.threshold == pytest.approx(1.0)

    # And the instrument's own three-state verdict, which is where the interval lives.
    assert reading.holds is True
    assert reading.ad_high < reading.threshold


def test_the_two_rung_zero_estimators_disagree_and_it_is_published_as_a_transfer():
    """The disagreement is a finding rather than a bug, so it comes back as a battery term."""
    run = annealed_run(rate=0.01, means=ar1(0.6, 60, seed=15))
    reading = adiabaticity(run, floors=FAST_TAU)
    assert not isinstance(reading, Refusal)
    transfer = tau_transfer(reading)
    assert transfer.value > 0
    assert transfer.name == "t21"
    assert "rate/regime.py" in transfer.method
    assert transfer.as_term().name == "t21"


# ---------------------------------------------------------------------------
# Clause 3: a width with its fit, validated against planted widths
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("planted_width", [10.0, 25.0, 58.0, 120.0])
def test_a_transition_width_is_fitted_with_its_fit_quality_and_recovers_a_planted_width(
    planted_width,
):
    """Four planted widths across a decade, each recovered to within five percent.

    The fit quality is not optional decoration on the reading, so it is asserted here: the width
    carries an interval, an r-squared, and the information-criterion margin over a straight line
    that is what separates a transition from a trend.
    """
    t = np.arange(400, dtype=float)
    y = _logistic(t, 0.0, 1.0, 200.0, planted_width) + np.random.default_rng(7).normal(0, 0.02, 400)

    fit = fit_transition(y, t, series="planted", criteria=FAST_FIT)
    assert not isinstance(fit, Refusal), getattr(fit, "render", lambda: fit)()
    assert fit.width == pytest.approx(planted_width, rel=0.05)
    assert fit.midpoint == pytest.approx(200.0, abs=2.0)
    assert fit.usable

    quality = fit.quality
    assert quality.identified
    assert quality.r2 > 0.9
    assert quality.delta_aicc_line >= 10.0
    assert quality.width_ci[0] < fit.width < quality.width_ci[1]
    assert quality.n == 400 and quality.n_boot_ok >= 20
    assert "AICc favours the transition" in fit.render()

    # And the unit the whole thing exists for.
    lead = lead_time(fit.midpoint - 0.69 * fit.width, fit)
    assert lead.widths == pytest.approx(0.69, abs=1e-6)
    assert "not comparable across runs" in lead.render()


def test_a_series_with_no_transition_refuses_rather_than_reporting_the_width_of_the_noise():
    """The other half of the clause. A width with a fit is only worth having if a bad fit refuses."""
    noise = np.random.default_rng(0).normal(0.0, 1.0, 200)
    out = fit_transition(noise, series="noise", criteria=FAST_FIT)
    assert isinstance(out, Refusal)
    assert out.reason is RefusalReason.BELOW_LOD
    assert out.statistics["delta_aicc_line"] < 10.0
    assert "cannot manufacture one" in out.remedy


# ---------------------------------------------------------------------------
# The real subject
# ---------------------------------------------------------------------------


def test_ad_runs_on_the_real_grpo_record_and_the_worst_step_is_the_last_one():
    """A real optimisation trace: real advantages, a real learning-rate schedule, real abstentions.

    The schedule decays linearly to zero, so its log derivative is small at every step and unbounded
    at the last one. That is the case a window maximum hides and per-step `Ad` shows, and it is not
    a contrived example: it is what the shipped schedule of a real trainer does.
    """
    run = open_fixture("long") if (FIXTURES / "long" / "runs").is_dir() else open_fixture("short")
    reading = adiabaticity(run, floors=FAST_TAU)
    if isinstance(reading, Refusal):
        # A bounded refusal is a correct answer here and the bound is the reading.
        assert reading.reason is RefusalReason.ABOVE_LOD_BELOW_LOQ
        assert reading.is_bounded
        return

    n_steps = len(run.steps.indices)
    assert len(reading.per_step) == n_steps - 1
    assert reading.parameter == "learning_rate"
    assert reading.worst_step == max(run.steps.indices)
    assert reading.per_step[-1].rate == pytest.approx(math.log(2.0), rel=1e-6), (
        "a schedule decaying linearly to zero halves on its final step, so d log lambda / dt is "
        "exactly ln 2 there"
    )
    assert reading.median_ad < reading.ad
    assert reading.tau.tau >= 0.0


def test_the_real_record_is_a_run_where_w2_7_declines_and_this_package_answers():
    """The second clause, on the real subject rather than on a synthetic one.

    The 200-step GRPO record's early group-mean series has an uncorrected lag-1 coefficient of
    -0.030, so `rate/regime.py` reports no relaxation time and `QUASI_STATIC` comes back `None`
    while the learning rate is halving on the final step. The corrected coefficient is +0.013 and
    its interval reaches 0.85 steps, which puts the upper end of `Ad` at 0.59 against a threshold of
    1, so the condition is answered and the answer is that the run is quasi-static.
    """
    if not (FIXTURES / "long" / "runs").is_dir():
        pytest.skip("this assertion is about the 200-step record specifically")
    run = open_fixture("long")

    alone = measure_regime(run).conditions[RegimeCondition.QUASI_STATIC]
    assert alone.holds is None
    assert "tau_relax is not available" in alone.detail

    reading = adiabaticity(run, floors=FAST_TAU)
    assert not isinstance(reading, Refusal)
    assert reading.holds is True
    assert reading.ad_high < reading.threshold

    answered = measure_regime(run, inputs=regime_inputs(reading)).conditions[
        RegimeCondition.QUASI_STATIC
    ]
    assert answered.holds is True
    assert answered.statistic == pytest.approx(reading.ad_high)

    # And the disagreement between the two rung-0 estimators, which on this run is the whole of
    # this package's estimate because the cheap one declined.
    transfer = tau_transfer(reading)
    assert transfer.value == pytest.approx(reading.tau.tau)
    assert "an absence rather than a zero" in transfer.method


def test_h4_refuses_on_every_channel_the_real_record_carries():
    """There is no behavioural transition in this run, so every channel has to refuse.

    Reporting a width here would be the confident wrong number this library exists to prevent: the
    logistic would fit something, the number would look like a transition width, and every lead
    scored against it would inherit the false precision. Two constant channels refuse as
    `RECORD_INCOMPLETE` and the rest as `BELOW_LOD` with the information criterion in the refusal.
    """
    run = open_fixture("long") if (FIXTURES / "long" / "runs").is_dir() else open_fixture("short")
    have = available_series(run)
    assert have, "the record carries no per-step numeric channel at all"

    verdicts: dict[str, str] = {}
    for name in ("group_mean", "reward", "reward_std", "grad_norm", "entropy"):
        if name not in have:
            continue
        values, indices = series_from_run(run, name)
        out = fit_transition(values, indices, series=name, criteria=FAST_FIT)
        assert isinstance(out, Refusal), (
            f"a transition width was reported for {name!r} on a run with no transition in it"
        )
        verdicts[name] = out.reason.name
    assert verdicts, "no channel was tested"
    assert set(verdicts.values()) <= {"BELOW_LOD", "RECORD_INCOMPLETE"}


def test_the_instrument_emits_or_refuses_on_the_real_record_and_never_raises():
    """Both instruments, through `estimate`, on a real record. Evidence or a Refusal, never both."""
    run = open_fixture("long") if (FIXTURES / "long" / "runs").is_dir() else open_fixture("short")
    for instrument in (
        Adiabaticity(run, floors=FAST_TAU),
        TransitionWidth(run, series="group_mean", criteria=FAST_FIT),
    ):
        reading = instrument.estimate(_context())
        if isinstance(reading, Refusal):
            assert reading.remedy.strip()
            assert reading.reason in RefusalReason
        else:
            assert reading.quantity in ("run.adiabaticity", "run.transition_width")
