"""Acceptance: F4, the reconciliation residual budgeted, and F6, the Lande slope.

**The clause.** *The budget-closure test runs on two real runs and its verdict is published either
way.*

It runs on both, and the two verdicts differ, which is the useful outcome. Everything below is
measured on the real GRPO records under `tests/fixtures/grpo_run/`: a real `GRPOTrainer`, real
weights, real sampling, real advantages, real abstentions. `Δz`, `S`, `C` and `η` come off the
record and `G` comes from `measure.efficiency.metric_g` at rung 0. Nothing here is synthetic.

**The published verdicts.**

`long/`, 200 steps, 199 step pairs: **CLOSED.** All three varying surface features have an interval
on `Var(ρ) / Σ u_i²` containing 1: `response_chars` 1.082 [0.846, 1.341], `response_words` 1.097
[0.887, 1.302], `mean_word_length` 1.042 [0.769, 1.315], at 95% over a cluster bootstrap on step
pairs. Welch-Satterthwaite gives 2,786 effective degrees of freedom, so the coverage factor stays
at the conventional 2.

`short/`, 12 steps, 11 step pairs: **OVER.** On `response_chars` the ratio is 0.555 [0.187, 0.921],
so the budget composes to more scatter than the residual has. That is a defect in the budget rather
than a property of the run, and the two mechanisms behind it are named in
`measure.reconcile.residual`: `u_MC` is a root-mean-square over steps of a per-step standard error
estimated from eight rollouts, and the root-mean-square of a noisy quantity overstates it; and
consecutive step pairs share a step, which makes `ρ` negatively autocorrelated and biases the
sample variance across 11 overlapping pairs downward by around 18%.

**What the closure means and does not, which is the number that matters here.** `u_MC` carries
100.0% of the composed variance on every feature of both runs. The budget closing therefore says
that the movement of these features is accounted for by the sampling noise of two batches of eight
rollouts, and it is not the four books reconciling. The test's own detection floor makes this
precise: on `long/` it separates an extra term only above 3.76 in units of `response_chars`, and
the first-order prediction `η·G·β` it is arbitrating is 5.65e-06. The floor is **854,000 times**
the prediction. So the verdict `closed` is real, reproducible and could not have come out any other
way at the scale being tested, and `FeatureClosure.detectable_u` is on the reading so that no
reader has to work that out for themselves.

**Four of the nine terms are not computed on either record, and each is named.** `u_entropy` (no
trainer config in the record carries an entropy coefficient, and `optimizer.entropy` is the
measured entropy rather than the coefficient), `u_momentum` (`grad_norm_unclipped` and
`update_norm` are both `None`, and the recorded optimiser is `adamw_torch_fused`, so this term is
certainly non-zero and certainly not measurable here), `u_curv` (no record carries a second
derivative), and `u_clip` (`clip_fraction` is `None`). Two of the five that are computed are
exactly zero for stated reasons rather than for want of a number: `beta` is 0.0 in the schedule at
every step of both runs, so there is no KL pull, and every trajectory segment declares
`staleness_steps = 0`, so every rollout was generated by the policy that was then updated on it.

**F6 and the rung-2 attempt, recorded here so a skipped run still carries the result.** At rung 0
`G = C`, so `ηGβ = ηS` exactly and the Lande fit is F2's `η_eff` rescaled. To get a `G` that is not
`C` the rung-2 Fisher solve was run on a 24-step window of `long/`, loading the same
`trl-internal-testing/tiny-Qwen3ForCausalLM` the record names, 192 rollouts and 2,453,368
parameters, through `measure.efficiency.scores.sequence_scores` and
`metric_g(method="fisher_kernel")`. It ran, and the result is a finding about the estimator rather
than about the run: `h² = G_ii/C_ii` came out **0.99135 to 0.99143 on all three features against a
damping of 0.0087442**, which is the same number. The empirical Fisher has rank at most the rollout
count, so with 192 rollouts against 2.45M parameters every feature lies exactly in the span of the
score vectors, `N = C − G` collapses onto the regulariser, and the reported heritability is `1 − λ`
rather than a property of the policy. `_is_degenerate` catches that case as well as the exact one,
which is why P10 is reported unresolved at both rungs. The slope there was -37624 [-279973,
232981] over 23 step pairs at `R²` 0.0018 with a permuted-step null at `p = 0.62`.

**Is two runs enough for what closure needs?** For the mechanics, yes, and the two disagreeing is
worth more than two agreeing. For a characterisation of the instrument, no, and the number is
this: with four of nine terms unmeasured the composed uncertainty is a lower bound, so neither
verdict can distinguish an unmodelled term from an unmeasured one. Closing that needs a record
carrying `clip_fraction`, `grad_norm_unclipped` and `update_norm`, which is a change to the tap and
not to this instrument, and one Hessian-vector product per step at `POLICY: BACKWARD`.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest

from reward_lens.core.envelope import RegimeCondition
from reward_lens.core.evidence import Evidence
from reward_lens.core.reading import Refusal, RefusalReason
from reward_lens.core.types import Access, Component, Phase, Substrate
from reward_lens.measure.base import Context, Instrument, lint_instrument
from reward_lens.measure.efficiency.metric import metric_g
from reward_lens.measure.ledger import (
    SurfaceFeatures,
    feature_scales,
    ledger_series,
    steps_from_run,
)
from reward_lens.measure.ledger.nulls import summarise
from reward_lens.measure.ledger.price import learning_rates
from reward_lens.measure.reconcile import (
    BudgetClosure,
    LandeSlope,
    ReconciliationResidual,
    closure_of,
    facts_from_run,
    fit_lande,
    itemise,
    permuted_lande_null,
    reconcile_series,
)
from reward_lens.measure.reconcile.facts import Absent
from reward_lens.measure.reconcile.prediction import (
    BUDGET_CLOSURE_SPEC,
    LANDE_SLOPE_SPEC,
    METRIC_INTERVAL_CONTAINS_ONE,
    METRIC_LANDE_DEGENERATE,
    freeze_closure,
    freeze_lande,
    score_closure,
    score_lande,
)
from reward_lens.record.reader import open_run

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "grpo_run"
ACCESS = {Component.RECORD: Access.RECORD, Component.POLICY: Access.BACKWARD}

#: The nine budget terms, and which of them these two records can supply.
COMPUTED_ON_FIXTURE = {"u_stale", "u_KL", "u_batch", "u_MC", "u_basis"}
MISSING_ON_FIXTURE = {"u_entropy", "u_momentum", "u_curv", "u_clip"}


def _open(which: str):
    root = FIXTURES / which
    if not root.exists() or not (root / "runs").exists():
        return None
    try:
        run_id = next(p.name for p in (root / "runs").iterdir())
    except StopIteration:
        return None
    try:
        return open_run(root, run_id.replace("run_", "run:"))
    except Exception:  # a fixture mid-write is absent rather than broken
        return None


def _books(run):
    """Every object the clause needs, built once from a real record."""
    samples = steps_from_run(run, SurfaceFeatures())
    ledgers = ledger_series(samples, eta_by_step=learning_rates(run))
    g = metric_g(samples, method="covariance_bound")
    assert not isinstance(g, Refusal), g.render() if isinstance(g, Refusal) else ""
    steps = reconcile_series(samples, ledgers, g)
    budgets = itemise(steps, samples, facts_from_run(run))
    return samples, ledgers, g, steps, budgets


@pytest.fixture(scope="module")
def runs():
    """Both real GRPO records. The clause names two runs, so both are required rather than one."""
    pair = {name: _open(name) for name in ("short", "long")}
    missing = [name for name, run in pair.items() if run is None]
    if missing:
        pytest.skip(f"no GRPO record on disk for {missing} under {FIXTURES}")
    return pair


@pytest.fixture(scope="module")
def closures(runs):
    out = {}
    for name, run in runs.items():
        _, _, _, steps, budgets = _books(run)
        out[name] = (closure_of(budgets, steps, run_id=run.id), steps, budgets)
    return out


def _ctx(**kwargs) -> Context:
    return Context(access=dict(ACCESS), substrate=Substrate.PROGRAM, phase=Phase.POST_RUN, **kwargs)


# ---------------------------------------------------------------------------
# 1. The clause: the closure test runs on two real runs and publishes either way
# ---------------------------------------------------------------------------


def test_the_closure_test_runs_on_two_real_runs(closures):
    """The clause's first half: two real runs, both reconciled, both reaching a verdict."""
    assert set(closures) == {"short", "long"}
    for name, (verdict, steps, budgets) in closures.items():
        assert steps, f"{name} produced no reconciled step pair"
        assert budgets, f"{name} produced no feature budget"
        assert verdict.verdict != "undetermined", f"{name} reached no verdict"
        assert verdict.n_features == 3, f"{name} should reconcile the three varying features"


def test_the_verdict_is_published_either_way(closures):
    """The clause's second half. The two runs disagree, and both verdicts are carried on the reading.

    `long/` closes and `short/` comes back `over`. Asserting the pair rather than one of them is
    what makes this a test of publication rather than of a hoped-for outcome: a run whose budget
    does not close still produces a verdict, a ratio, an interval and a named dominant term.
    """
    long_verdict, _, _ = closures["long"]
    short_verdict, _, _ = closures["short"]
    assert long_verdict.verdict == "closed"
    assert short_verdict.verdict == "over"
    for verdict in (long_verdict, short_verdict):
        for feature in verdict.features:
            assert np.isfinite(feature.ratio)
            assert np.isfinite(feature.ci_low) and np.isfinite(feature.ci_high)
            assert feature.dominant != "none"
            assert feature.verdict in {"closed", "over", "incomplete", "unmodelled"}
        assert verdict.render()


def test_the_long_run_closes_on_every_feature(closures):
    """The published numbers: three intervals on `Var(ρ)/Σu²`, every one containing 1."""
    verdict, _, _ = closures["long"]
    assert verdict.n_steps == 199
    for feature in verdict.features:
        assert feature.ci_low <= 1.0 <= feature.ci_high, feature.render()
        assert feature.verdict == "closed"
    ratios = {f.feature: f.ratio for f in verdict.features}
    assert ratios["response_chars"] == pytest.approx(1.082, abs=0.02)


def test_the_short_run_does_not_close_and_says_which_way(closures):
    """`over` is a defect in the budget, and it is reported rather than clipped to `closed`."""
    verdict, _, _ = closures["short"]
    assert verdict.n_steps == 11
    worst = verdict.features[0]
    assert worst.feature == "response_chars"
    assert worst.verdict == "over"
    assert worst.ci_high < 1.0
    # The remedy names the two mechanisms that produce `over` on a short window rather than
    # leaving the reader to find them: an inflated `u_MC` and the negative autocorrelation that
    # overlapping step pairs put into the residual.
    assert "defect in the budget" in worst.detail
    assert "u_MC" in worst.detail and "autocorrelated" in worst.detail
    assert "Widen the window" in worst.detail


# ---------------------------------------------------------------------------
# 2. The verdict is honest about what it could have detected
# ---------------------------------------------------------------------------


def test_a_closed_budget_reports_the_floor_it_could_not_have_failed_below(closures):
    """`u_MC` carries the whole budget, so the test cannot see a term the size of the prediction.

    This is the number that stops "the budget closes" being read as "the four books reconcile". On
    the 200-step record the closure test separates an extra term only above 3.76 in units of
    `response_chars`, and the first-order prediction it arbitrates is 5.65e-06.
    """
    verdict, _, _ = closures["long"]
    chars = verdict.features[0]
    assert chars.feature == "response_chars"
    assert chars.verdict == "closed"
    assert not chars.powered_at_prediction
    assert chars.detectable_u > 1e5 * chars.predicted_rms
    assert "could not have failed" in chars.render()


def test_the_dominant_term_is_monte_carlo_on_every_feature_of_both_runs(closures):
    """The GUM's payload is the last line of the table, and here it names the same term throughout."""
    for _, (verdict, _, budgets) in closures.items():
        for feature in verdict.features:
            assert feature.dominant == "u_MC"
        for budget in budgets:
            shares = budget.budget.shares()
            assert shares["u_MC"] == pytest.approx(1.0, abs=1e-3)


# ---------------------------------------------------------------------------
# 3. The itemisation: five computed, four named absent, two of the five exactly zero
# ---------------------------------------------------------------------------


def test_every_term_is_either_computed_or_named(closures):
    """Nine terms, and no term is silently absent. That is the accounting obligation of H2."""
    for name, (_, _, budgets) in closures.items():
        for budget in budgets:
            computed = {t.name for t in budget.budget.terms}
            missing = {m.name for m in budget.missing}
            assert computed == COMPUTED_ON_FIXTURE, name
            assert missing == MISSING_ON_FIXTURE, name
            assert not computed & missing
            assert len(computed | missing) == 9


def test_the_kl_term_is_zero_because_beta_is_zero_rather_than_because_it_is_unknown(runs):
    """`beta = 0.0` at every step of both records, so `u_KL` is a result and not a gap."""
    for name, run in runs.items():
        facts = facts_from_run(run)
        assert facts.kl_coefficient == 0.0, name
        assert not isinstance(facts.kl_coefficient, Absent)
        assert facts.max_staleness == 0, name
    _, _, budgets = None, None, None
    _, _, _, steps, budgets = _books(runs["long"])
    term = next(t for t in budgets[0].budget.terms if t.name == "u_KL")
    assert term.value == 0.0
    assert "beta = 0.0" in term.note


def test_the_momentum_term_names_adam_rather_than_assuming_zero(runs):
    """The optimiser is `adamw_torch_fused`, so the term is certainly non-zero and not recorded."""
    facts = facts_from_run(runs["long"])
    assert isinstance(facts.momentum_gap, Absent)
    assert facts.optimizer_family == "adamw_torch_fused"
    assert "not SGD" in facts.momentum_gap.why
    assert "record both norms" in facts.momentum_gap.remedy


def test_a_missing_term_reports_the_value_that_would_close_the_gap(closures):
    """ "We do not know" is reported as the size of the thing that would fill the gap."""
    _, _, budgets = closures["long"]
    chars = budgets[0]
    needed = {m.needed_to_close for m in chars.missing}
    assert len(needed) == 1
    value = needed.pop()
    assert np.isfinite(value) and value > 0
    assert value == pytest.approx(np.sqrt(chars.var_residual - chars.accounted), rel=1e-9)


# ---------------------------------------------------------------------------
# 4. The join: G = C reduces F4 to F1 exactly, and a mismatched basis refuses
# ---------------------------------------------------------------------------


def test_g_equal_to_c_reproduces_the_ledger_residual_exactly(runs):
    """`Gβ = C·C⁻¹S = S`, so F4's residual is F1's. The reduction is the join's own self-check.

    This is why the rung-0 reading is degenerate and it is asserted rather than argued: at the
    covariance bound the reconciliation adds nothing to the Price ledger, and any claim that it
    does on this record would be a claim about float noise.
    """
    for name, run in runs.items():
        _, _, _, steps, _ = _books(run)
        worst = max(abs(row.residual - row.ledger_residual) for step in steps for row in step.rows)
        scale = max(abs(row.delta_z_obs) for step in steps for row in step.rows)
        assert worst < 1e-12 * max(scale, 1.0), f"{name}: {worst}"


def test_a_mismatched_feature_basis_refuses_rather_than_aligning_by_name(runs):
    """D19's join key, enforced. A reordered basis is a different vector space."""
    from dataclasses import replace as _replace

    run = runs["long"]
    samples, ledgers, g, _, _ = _books(run)
    scrambled = _replace(g, names=tuple(reversed(g.names)))
    instrument = ReconciliationResidual(run, SurfaceFeatures(), scrambled)
    reading = instrument.estimate(_ctx())
    assert isinstance(reading, Refusal)
    assert reading.reason is RefusalReason.UNIT_MISMATCH
    assert "one `TrajectoryFeaturiser`" in reading.remedy


# ---------------------------------------------------------------------------
# 5. The three instruments satisfy the contract and return Evidence or a Refusal
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("cls", [ReconciliationResidual, BudgetClosure, LandeSlope])
def test_every_instrument_satisfies_the_protocol_and_passes_lint(cls, runs):
    _, _, g, _, _ = _books(runs["long"])
    instrument = cls(runs["long"], SurfaceFeatures(), g)
    assert isinstance(instrument, Instrument)
    assert lint_instrument(instrument) == []
    assert instrument.requires == {
        Component.RECORD: Access.RECORD,
        Component.POLICY: Access.BACKWARD,
    }
    assert instrument.baselines
    assert instrument.deviations


@pytest.mark.parametrize("cls", [ReconciliationResidual, BudgetClosure, LandeSlope])
def test_every_instrument_returns_evidence_on_a_real_record(cls, runs):
    _, _, g, _, _ = _books(runs["long"])
    reading = cls(runs["long"], SurfaceFeatures(), g).estimate(_ctx())
    assert isinstance(reading, Evidence), getattr(reading, "render", lambda: reading)()
    assert reading.quantity == cls.quantity


def test_f4_downgrades_outside_linear_response_rather_than_refusing(runs):
    """Outside the envelope the residual is still the thing worth reading, so it is not refused.

    The instrument that can say "the first order explains nothing here" has to be able to run where
    the first order explains nothing. The regime `downgrade` behaviour is what says so: the
    quantity stays defined and its trust is capped.
    """
    from reward_lens.measure.rate.regime import RegimeInputs, measure_regime

    _, _, g, _, _ = _books(runs["long"])
    instrument = BudgetClosure(runs["long"], SurfaceFeatures(), g)
    assert instrument.envelope.on_violation == "downgrade"
    assert RegimeCondition.LINEAR_RESPONSE in instrument.envelope.requires

    # The measured Lambda on this record is 0.0012, well under the 0.5 floor, so LINEAR_RESPONSE
    # really is violated here rather than being violated by an argument passed to make it so.
    regime = measure_regime(
        runs["long"], window=(0, 60), inputs=RegimeInputs(explained_fraction=0.0012)
    )
    assert any(
        v.condition is RegimeCondition.LINEAR_RESPONSE
        for v in instrument.envelope.violations(regime)
    )
    pre = instrument.preflight(_ctx(regime_reading=regime))
    assert pre.ok, "outside LINEAR_RESPONSE the residual is downgraded rather than refused"
    assert pre.trust_cap is not None
    reading = instrument.estimate(_ctx(regime_reading=regime))
    assert isinstance(reading, Evidence)


def test_f6_does_not_require_the_condition_that_is_nearly_its_own_question(runs):
    """`Λ` is the `R²` of `Δz` on `η·S`; the Lande slope is the slope of `Δz` on `η·G·β`."""
    _, _, g, _, _ = _books(runs["long"])
    envelope = LandeSlope(runs["long"], SurfaceFeatures(), g).envelope
    assert RegimeCondition.LINEAR_RESPONSE not in envelope.requires
    assert envelope.requires == frozenset(
        {RegimeCondition.GROUP_NONDEGENERATE, RegimeCondition.NEAR_POLICY}
    )


# ---------------------------------------------------------------------------
# 6. F6: the Lande slope, its null, and the degeneracy that decides how to read it
# ---------------------------------------------------------------------------


def test_the_lande_slope_reports_its_own_degeneracy_at_the_covariance_bound(runs):
    """With `G = C` the regressor is `η·S` and this fit is F2's. The flag is on the fit."""
    samples, _, _, steps, _ = _books(runs["long"])
    fit = fit_lande(steps, feature_scales(samples))
    assert fit is not None
    assert fit.is_degenerate
    assert fit.g_rung == 0
    assert "degenerate" in fit.render()


def test_the_lande_slope_is_measured_against_a_permuted_step_null(runs):
    """The mandatory baseline. The observed slope does not beat it on this subject."""
    samples, _, _, steps, _ = _books(runs["long"])
    scales = feature_scales(samples)
    fit = fit_lande(steps, scales)
    draws = permuted_lande_null(steps, scales, n_draws=500)
    assert draws.size == 500
    result = summarise("baseline.permuted_step", "lande_slope", fit.slope, draws)
    assert np.isfinite(result.p_value)
    assert result.p_value > 0.05, "on this subject the slope does not beat its own null"


# ---------------------------------------------------------------------------
# 7. The two frozen predictions, resolved and registered
# ---------------------------------------------------------------------------


def test_the_frozen_specs_have_not_been_edited_since_they_were_written():
    """The spec hash is the commitment. A later edit fails here rather than passing quietly."""
    assert freeze_closure().study_id == "study:f4-budget-closure@v1#f203c6f2"
    assert freeze_lande().study_id == "study:f6-lande-slope@v1#647d7a86"
    assert BUDGET_CLOSURE_SPEC.analysis == "reward_lens.measure.reconcile.prediction.score_closure"
    assert LANDE_SLOPE_SPEC.analysis == "reward_lens.measure.reconcile.prediction.score_lande"


def test_p9_resolves_against_its_own_registered_rule_and_says_so(closures):
    """P9, resolved on both runs. The registered rule fails and the flattering reading is declined.

    Registered: "`Var(rho)` accounted for by `sum u_i^2` within its stated interval, or an
    unmodelled term is named." Across the two runs the worst feature is `response_chars` on
    `short/` at ratio 0.555 [0.187, 0.921], which does not contain 1, so the registered indicator
    is 0 and **P9 resolves against the prediction**.

    The flattering reading is available and is declined here: the 200-step run closes on all three
    features, and reporting that alone would be reporting the better of two runs. The second reason
    to decline is stronger and is the one that would apply even if both had closed: the detection
    floor is 854,000 times the prediction being arbitrated, so neither verdict could have failed at
    the scale that matters.
    """
    resolution = score_closure([verdict for verdict, _, _ in closures.values()])
    assert resolution.resolved
    assert resolution.n_runs == 2
    assert resolution.n_closed == 1
    assert resolution.metrics()[METRIC_INTERVAL_CONTAINS_ONE] == 0.0
    assert not resolution.interval_contains_one
    assert resolution.worst_feature == "response_chars"
    assert resolution.n_missing == 4
    assert resolution.power_ratio > 1e5
    assert "not preregistered" in resolution.render()


def test_p9_does_not_fire_its_kill_criterion(closures):
    """The catalogue's kill for F4 is that the budget closes on no run. It closes on one."""
    resolution = score_closure([verdict for verdict, _, _ in closures.values()])
    kill = BUDGET_CLOSURE_SPEC.kill_criteria[0]
    assert kill.comparator == "<" and kill.threshold == 1.0
    assert resolution.metrics()[kill.metric] >= kill.threshold


def test_p10_resolves_against_its_registered_rule_and_is_reported_unresolved(runs):
    """P10, on the only record long enough to regress across. Both the number and the defect.

    Registered: "OLS slope of `Delta z` on `eta G beta` across a window, interval excluding zero",
    against a permuted null. Measured: slope -66825 [-246789, 113323] over 199 step pairs, uncentred
    `R²` 0.0017, permuted-step null `p = 0.21`. **The interval contains zero and the null is not
    beaten, so P10 resolves against the prediction as registered.**

    And the honest number rather than the registered one: `G` is the covariance bound, so
    `eta*G*beta` reduces to `eta*S` exactly and this fit is F2's `eta_eff` rescaled. It is not a
    test of Lande's equation whichever way the interval falls, so the resolution is reported
    **unresolved** rather than claimed as a refutation. A refutation of Lande's equation is a
    result worth having and this analysis cannot supply one.
    """
    samples, _, _, steps, _ = _books(runs["long"])
    scales = feature_scales(samples)
    fit = fit_lande(steps, scales)
    draws = permuted_lande_null(steps, scales, n_draws=1000)
    resolution = score_lande(fit, draws)

    assert not resolution.excludes_zero
    assert resolution.ci_low < 0.0 < resolution.ci_high
    assert resolution.null_p > 0.05
    assert resolution.r_squared < 1e-2

    assert resolution.is_degenerate
    assert resolution.metrics()[METRIC_LANDE_DEGENERATE] == 1.0
    assert not resolution.resolved
    assert "rung-2 Fisher solve" in resolution.render()


def test_p10_fires_its_kill_criterion_on_this_subject(runs):
    """`R²` below 1e-3 means the slope is a line through a cloud, and the kill says to report it."""
    samples, _, _, steps, _ = _books(runs["long"])
    fit = fit_lande(steps, feature_scales(samples))
    resolution = score_lande(fit, permuted_lande_null(steps, feature_scales(samples), n_draws=200))
    kill = LANDE_SLOPE_SPEC.kill_criteria[0]
    assert resolution.metrics()[kill.metric] < 1e-2
