"""``reward_lens.record`` — the canonical process record and its store.

Everything in Plane B and Plane C reads this and nothing else. If a quantity cannot be computed
from a `Run`, it is not a quantity this library reports.

Torch-free, like the rest of the core. The whole hierarchy is dataclasses, ints, floats and numpy
arrays, and the tensor store holds references rather than tensors: `StoredRef` points at bytes,
`RecomputeRef` says what to run to get them back, and `AbsentRef` says honestly that they are not
here. That third member is the reason a record of a 70B run fits on a laptop.

`scores.py` (the `ScoreTree`), `labels.py` (`Blind[T]`) and `arms.py` (`CouplingSpec`) fill the
three seams the schema left typed. The payloads round-trip through the kernel's `ValueCodec`, which
cost one `register_payload` decorator each and no change here, so the seams held.
"""

from __future__ import annotations

from reward_lens.record.arms import (
    ABSENT,
    Absent,
    Arm,
    ArmDivergence,
    ArmID,
    ArmSet,
    ArmSpecError,
    CouplingSpec,
    KeyDivergence,
    apply_overrides,
    arm_from_run,
    check_divergence,
    check_runs,
    flatten_config,
    guard_comparison,
    independent_seeds,
    run_material,
    shared_seeds,
)
from reward_lens.record.compaction import (
    CompactionEvent,
    CompactionSummary,
    crosses,
    events_in_window,
)
from reward_lens.record.labels import (
    Blind,
    LabelLeak,
    LabelQuality,
    LabelRead,
    LabelValue,
    OracleFrame,
    ReadPurpose,
    RolloutFrame,
    adjudicate,
    adjudicate_frame,
    blind,
    blocked_names,
    check_detector,
    is_blocked,
    label_reads,
    split_trajectory,
)
from reward_lens.record.provenance import (
    PolicyMixture,
    PolicyVersionID,
    SamplingMeta,
    SegmentProvenance,
    TilingError,
    check_tiling,
    policy_mixture,
    policy_versions,
    single_segment,
)
from reward_lens.record.reader import (
    PartitionedStepStream,
    ReadStats,
    RecordNotFound,
    RecordReader,
    open_run,
)
from reward_lens.record.schema import (
    RECORD_SCHEMA_VERSION,
    ComponentRef,
    EstimatorSpec,
    FeatureID,
    Group,
    GroupID,
    GroupStats,
    InMemoryStepStream,
    InstrumentEffect,
    OptimizerTelemetry,
    ProbeResult,
    RecordSamplingPolicy,
    RegimeDeclaration,
    Run,
    RunID,
    RunKind,
    RunLineage,
    SamplingCorrection,
    SamplingScheme,
    StalenessDistribution,
    Step,
    StepStream,
    TaskID,
    Trajectory,
    TrajectoryID,
    group_id,
    make_trajectory,
    run_id,
    task_id,
    trajectory_id,
)
from reward_lens.record.scores import (
    AbstentionCensus,
    AllAbstainedWarning,
    CounterfactualResult,
    DeadZone,
    DuplicateNodeName,
    GraderCallRef,
    GroupContext,
    GroupGate,
    GroupScores,
    Leaf,
    Lexicographic,
    Mask,
    MissingFeature,
    MissingGroupStatistic,
    Override,
    Piecewise,
    PredicateRef,
    Product,
    ScoreContext,
    ScoreTree,
    UnknownNode,
    WeightedSum,
    ablation_deltas,
    census,
    counterfactual,
    deadzone,
    evaluate,
    group_scores,
    is_additive,
    overrides,
    replay_advantages,
)
from reward_lens.record.tensors import (
    ABSENCE_REFUSAL,
    AbsenceReason,
    AbsentRef,
    CaptureRef,
    CaptureSpec,
    Engine,
    Recomputer,
    RecomputeRef,
    StoredRef,
    TensorRef,
    TensorStore,
    TokenTensorRef,
    honour,
    residual_bytes,
    resolve,
    resolve_all,
)
from reward_lens.record.turns import (
    ToolCall,
    Turn,
    TurnRole,
    logprob_mismatch,
    mask_policy_signature,
    renumber,
)
from reward_lens.record.writer import RecordFormat, RecordWriter, WriteReport

__all__ = [
    # the hierarchy
    "Run",
    "Step",
    "Group",
    "Trajectory",
    "Turn",
    "ToolCall",
    "TurnRole",
    "make_trajectory",
    "renumber",
    # identity
    "RunID",
    "GroupID",
    "TrajectoryID",
    "TaskID",
    "FeatureID",
    "PolicyVersionID",
    "RunKind",
    "run_id",
    "group_id",
    "trajectory_id",
    "task_id",
    # run-level structures
    "ComponentRef",
    "RunLineage",
    "RegimeDeclaration",
    "RecordSamplingPolicy",
    "SamplingScheme",
    "SamplingCorrection",
    # step-level structures
    "OptimizerTelemetry",
    "StalenessDistribution",
    "ProbeResult",
    "InstrumentEffect",
    # group-level structures
    "EstimatorSpec",
    "GroupStats",
    # provenance and compaction
    "SegmentProvenance",
    "SamplingMeta",
    "PolicyMixture",
    "TilingError",
    "check_tiling",
    "single_segment",
    "policy_mixture",
    "policy_versions",
    "CompactionEvent",
    "CompactionSummary",
    "crosses",
    "events_in_window",
    # tensors
    "TensorRef",
    "StoredRef",
    "RecomputeRef",
    "ABSENCE_REFUSAL",
    "AbsentRef",
    "AbsenceReason",
    "TokenTensorRef",
    "CaptureSpec",
    "CaptureRef",
    "Engine",
    "Recomputer",
    "TensorStore",
    "resolve",
    "resolve_all",
    "honour",
    "residual_bytes",
    # storage
    "RECORD_SCHEMA_VERSION",
    "RecordWriter",
    "RecordFormat",
    "WriteReport",
    "RecordReader",
    "RecordNotFound",
    "ReadStats",
    "PartitionedStepStream",
    "StepStream",
    "InMemoryStepStream",
    "open_run",
    # statistics the regime reading is built from
    "logprob_mismatch",
    "mask_policy_signature",
    # the score tree
    "ScoreTree",
    "Leaf",
    "WeightedSum",
    "Product",
    "Override",
    "Lexicographic",
    "Piecewise",
    "GroupGate",
    "Mask",
    "PredicateRef",
    "GraderCallRef",
    "ScoreContext",
    "GroupContext",
    "GroupScores",
    "CounterfactualResult",
    "AbstentionCensus",
    "DeadZone",
    "UnknownNode",
    "DuplicateNodeName",
    "MissingFeature",
    "MissingGroupStatistic",
    "AllAbstainedWarning",
    "evaluate",
    "counterfactual",
    "census",
    "deadzone",
    "ablation_deltas",
    "replay_advantages",
    "group_scores",
    "overrides",
    "is_additive",
    # blinded labels
    "Blind",
    "LabelValue",
    "LabelQuality",
    "LabelRead",
    "ReadPurpose",
    "LabelLeak",
    "RolloutFrame",
    "OracleFrame",
    "blind",
    "adjudicate",
    "adjudicate_frame",
    "label_reads",
    "check_detector",
    "split_trajectory",
    "is_blocked",
    "blocked_names",
    # arms and coupling
    "Arm",
    "ArmSet",
    "ArmID",
    "ArmSpecError",
    "CouplingSpec",
    "ArmDivergence",
    "KeyDivergence",
    "Absent",
    "ABSENT",
    "shared_seeds",
    "independent_seeds",
    "check_divergence",
    "check_runs",
    "guard_comparison",
    "arm_from_run",
    "run_material",
    "flatten_config",
    "apply_overrides",
]
