"""Series B, grader structure: is this thing a scalar, and what is it made of.

A pairwise comparison flow decomposes into a gradient part, a curl part and a harmonic part, and only
the first is representable by any scalar reward. Reporting one intransitivity number throws away the
half that says what to do about it.

**Read `nulls.transitive_baseline` before reading any curl mass from this package.** A comparison
recorded as a bare win or loss is a sign rather than a margin, and a sign flow is not a gradient even
under a perfect total order: on the complete graph ``K_n`` a transitive tournament has curl mass
exactly ``(n-2)/(3n)``. That floor is an encoding artifact with no intransitivity in it, it is larger
than most reported effects, and subtracting it changes conclusions.

This ``__init__`` is deliberately thin: each module is importable directly, and the exports are
merged here.

One name is deliberately absent. ``summarise`` is defined by both `tournament` and `composition`,
with unrelated meanings and unrelated return types, so there is no bare ``summarise`` in this
namespace: a flat re-export would have let import order decide which one a caller got. The two
travel as `summarise_tournament` and `summarise_composition`, and the originals stay reachable at
their own modules under the names their own tests use.
"""

from __future__ import annotations

from reward_lens.measure.composition.abstention import (
    AbstentionRate,
    AbstentionReading,
    BaselineShift,
    SilentZeroRate,
    as_the_framework_used_it,
    baseline_shifts,
    read_census,
)
from reward_lens.measure.composition.composition import (
    CompositionInstrument,
    CompositionSummary,
    CompositionTree,
    CounterfactualComposition,
    CounterfactualReading,
    NullLeak,
    auto_constant,
    null_leak,
    null_probe,
    offset_node,
)
from reward_lens.measure.composition.composition import (
    summarise as summarise_composition,
)
from reward_lens.measure.composition.hodge import (
    CURL_MASS_ENVELOPE,
    HALDANE_ANSCOMBE,
    MIN_REPLICATIONS_FOR_NULLS,
    ComparisonFlow,
    CurlMass,
    Edge,
    FlowScale,
    HodgeSplit,
    PairCount,
    Triangle,
    betti1,
    curl_mass_of_payload,
    curl_operator,
    disjoint_union,
    edge_flow,
    hodge_split,
    incidence,
    split_flow,
    triangles,
)
from reward_lens.measure.composition.nulls import (
    CONTROL_FLOOR,
    RELIABILITY_FLOOR,
    AnisotropyResult,
    BootstrapResult,
    ProfileBaseline,
    SplitHalfResult,
    bradley_terry_bootstrap,
    bradley_terry_scores,
    curl_anisotropy,
    random_profile_baseline,
    split_half_reliability,
    transitive_baseline,
    transitive_curl_mass_complete,
)

# `RANDOM_TOURNAMENT` and `bank_from_scores` are defined identically in `revealed` and `tournament`;
# imported once, from the module that owns them.
from reward_lens.measure.composition.revealed import (
    AFRIAT_ENVELOPE,
    CURL_MASS,
    RANDOM_TOURNAMENT,
    AfriatIndex,
    AfriatResult,
    ComparisonSet,
    FeedbackArcs,
    GarpReport,
    HoutmanMaksResult,
    MoneyPumpResult,
    afriat_index,
    afriat_index_of,
    bank_from_payload,
    bank_from_score_panels,
    bank_from_scores,
    direct_preference,
    garp,
    garp_violations,
    houtman_maks,
    min_feedback_arcs,
    money_pump,
    random_tournament_index,
    transitive_closure,
)
from reward_lens.measure.composition.sepnorm import (
    SEP_DISTANCE_ENVELOPE,
    SepDistance,
    SepDistanceBound,
    column_mean_bound,
    contraction_factor,
    report_line,
    sep_distance,
    sep_distance_of_payload,
    triple_scan,
)
from reward_lens.measure.composition.tournament import (
    B6_INSTRUMENTS,
    RANDOM_DESIGN,
    TOTAL_ORDER,
    TOURNAMENT_ENVELOPE,
    ComparisonConnectivity,
    CondorcetRate,
    CondorcetReading,
    Connectivity,
    SmithSetSize,
    TournamentSummary,
    algebraic_connectivity,
    bank_from_invariance_payload,
    condorcet,
    copeland_scores,
    copeland_slater_split,
    copeland_winners,
    kemeny,
    pair_to_add,
    random_design_lambda2,
    random_tournament_summary,
    slater,
    slater_winners,
    smith_set,
)
from reward_lens.measure.composition.tournament import (
    summarise as summarise_tournament,
)

__all__: list[str] = [
    "AFRIAT_ENVELOPE",
    "B6_INSTRUMENTS",
    "CONTROL_FLOOR",
    "CURL_MASS",
    "CURL_MASS_ENVELOPE",
    "HALDANE_ANSCOMBE",
    "MIN_REPLICATIONS_FOR_NULLS",
    "RANDOM_DESIGN",
    "RANDOM_TOURNAMENT",
    "RELIABILITY_FLOOR",
    "SEP_DISTANCE_ENVELOPE",
    "TOTAL_ORDER",
    "TOURNAMENT_ENVELOPE",
    "AbstentionRate",
    "AbstentionReading",
    "AfriatIndex",
    "AfriatResult",
    "AnisotropyResult",
    "BaselineShift",
    "BootstrapResult",
    "ComparisonConnectivity",
    "ComparisonFlow",
    "ComparisonSet",
    "CompositionInstrument",
    "CompositionSummary",
    "CompositionTree",
    "CondorcetRate",
    "CondorcetReading",
    "Connectivity",
    "CounterfactualComposition",
    "CounterfactualReading",
    "CurlMass",
    "Edge",
    "FeedbackArcs",
    "FlowScale",
    "GarpReport",
    "HodgeSplit",
    "HoutmanMaksResult",
    "MoneyPumpResult",
    "NullLeak",
    "PairCount",
    "ProfileBaseline",
    "SepDistance",
    "SepDistanceBound",
    "SilentZeroRate",
    "SmithSetSize",
    "SplitHalfResult",
    "TournamentSummary",
    "Triangle",
    "afriat_index",
    "afriat_index_of",
    "algebraic_connectivity",
    "as_the_framework_used_it",
    "auto_constant",
    "bank_from_invariance_payload",
    "bank_from_payload",
    "bank_from_score_panels",
    "bank_from_scores",
    "baseline_shifts",
    "betti1",
    "bradley_terry_bootstrap",
    "bradley_terry_scores",
    "column_mean_bound",
    "condorcet",
    "contraction_factor",
    "copeland_scores",
    "copeland_slater_split",
    "copeland_winners",
    "curl_anisotropy",
    "curl_mass_of_payload",
    "curl_operator",
    "direct_preference",
    "disjoint_union",
    "edge_flow",
    "garp",
    "garp_violations",
    "hodge_split",
    "houtman_maks",
    "incidence",
    "kemeny",
    "min_feedback_arcs",
    "money_pump",
    "null_leak",
    "null_probe",
    "offset_node",
    "pair_to_add",
    "random_design_lambda2",
    "random_profile_baseline",
    "random_tournament_index",
    "random_tournament_summary",
    "read_census",
    "report_line",
    "sep_distance",
    "sep_distance_of_payload",
    "slater",
    "slater_winners",
    "smith_set",
    "split_flow",
    "split_half_reliability",
    "summarise_composition",
    "summarise_tournament",
    "transitive_baseline",
    "transitive_closure",
    "transitive_curl_mass_complete",
    "triangles",
    "triple_scan",
]
