"""Render every example and every number in README.md from code that ran.

The front page is the most-read prose in the project and it is the page where a number that came
from somewhere other than a run does the most damage. So the rule for README.md is stricter than
the rule for the rest of the documentation: an example is generated by this script, or it is not on
the page. Nothing is transcribed, nothing is "checked", nothing is true-as-of-when-it-was-written.

Three kinds of block, and the difference matters:

- **Captured.** A subprocess runs a shipped entry point and its stdout goes on the page verbatim.
  ``reward-lens capabilities`` and the card-plan example are both this. What the page shows is what
  the reader gets, including when that is disappointing.
- **Read from the registry.** The instrument and quantity counts, and the seventeen refusal
  reasons, come from ``reward_lens.core`` at generation time, the same source
  ``docs/gen_catalogue.py`` uses. A count on the page cannot disagree with the catalogue.
- **Extracted.** A measured number is lifted out of the artifact that produced it, by a pattern
  anchored on the surrounding sentence, and a pattern that no longer matches is a hard failure
  rather than a stale line. The extractors are the interesting part of this file: each one names
  the file it reads and what it expects to find there, so a number that moves in the tree takes the
  README with it instead of leaving it behind.

Markers in README.md delimit each block::

    <!-- generated: capabilities -->
    ...
    <!-- /generated: capabilities -->

Everything between them is owned by this script. Everything outside is prose a person wrote.

**Optional blocks.** Some blocks are extracted from large run artifacts that are published
separately rather than carried in the source tree. When such an artifact is not in the checkout the
block is *skipped*: the text already in README.md is left exactly as it stands, the reason is
printed, and ``--check`` still passes. That is deliberately different from drift. Drift means the
source is here and no longer says what the page quotes, which is a bug and fails the build. A
missing artifact means the page cannot be regenerated from this checkout at all, and rewriting it to
say less would be losing a real measurement to a packaging decision.

Run it:

    python scripts/gen_readme.py --check     # what CI runs; nonzero if the README has drifted
    python scripts/gen_readme.py --write     # regenerate the blocks in place
    python scripts/gen_readme.py --list      # the block names and their sizes

**What this script needs installed.** The base install plus the ``[verifier]`` extra, which is pure
Python and pulls nothing compiled. That is the same environment ``.github/workflows/docs.yml``
already builds, and it is deliberately not the full test environment: a generator that needs torch
to render a README would be a generator nobody runs.

**Determinism.** The captured commands are run with a fixed ``COLUMNS`` so Rich wraps identically
everywhere, with ``PYTHONHASHSEED`` fixed, and from the repository root so the relative paths that
appear in their output are stable. Every iteration over a set is sorted.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import textwrap
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"

#: Rich reads this to decide where to wrap. Pinned so a narrow terminal on somebody's laptop does
#: not rewrite the front page.
CAPTURE_COLUMNS = "92"

_MARKER_RE = re.compile(
    r"(?P<open><!-- generated: (?P<name>[a-z0-9-]+) -->\n)(?P<body>.*?)"
    r"(?P<close><!-- /generated: (?P=name) -->)",
    re.S,
)


class SourceDrift(RuntimeError):
    """An extractor could not find what it was told to find.

    Raised rather than warned, and raised with the file and the pattern in the message, because the
    failure mode this whole script exists to prevent is a page that keeps saying a number after the
    thing that measured it has moved.
    """


class MissingArtifact(RuntimeError):
    """A block's source artifact is not in this checkout, so the block cannot be regenerated.

    Not a failure. `SourceDrift` is for an artifact that is present and no longer says what the page
    quotes, which is a bug. This is for an artifact that was never here: a run output published
    elsewhere, or a directory a release tree does not carry. The block is skipped and whatever the
    README already says is left alone.
    """


class ReadmeDrift(RuntimeError):
    """``--check`` found a block on disk that does not match what regenerating produces."""


# ---------------------------------------------------------------------------
# Running things
# ---------------------------------------------------------------------------


def _env() -> dict[str, str]:
    env = dict(os.environ)
    env["COLUMNS"] = CAPTURE_COLUMNS
    env["PYTHONHASHSEED"] = "0"
    env["NO_COLOR"] = "1"
    env["TERM"] = "dumb"
    return env


def capture(argv: list[str], *, cwd: Path = ROOT, timeout: int = 600) -> str:
    """Run a command and return its stdout, or raise with enough to debug it.

    stderr is deliberately not merged in. A warning from a dependency is not part of the example,
    and merging the two streams would make the page churn every time somebody's numpy changes its
    deprecation schedule.
    """
    proc = subprocess.run(
        argv, cwd=cwd, env=_env(), capture_output=True, text=True, timeout=timeout
    )
    if proc.returncode != 0:
        raise SourceDrift(
            f"{' '.join(argv)} exited {proc.returncode}. The README shows this command's output, "
            f"so a command that fails here is a README that would be lying.\n"
            f"--- stderr ---\n{proc.stderr.strip()[-2000:]}"
        )
    return proc.stdout


def console_script(name: str) -> str:
    """Resolve a console script next to the interpreter running this file.

    Not ``shutil.which`` against a bare PATH. A generator that captures whichever ``reward-lens``
    happens to be first on somebody's PATH can render a README from a different installation than
    the one in the checkout, which is a page describing code that is not the code.
    """
    candidate = Path(sys.executable).parent / name
    if candidate.is_file():
        return str(candidate)
    found = shutil.which(name)
    if found is None:
        raise SourceDrift(
            f"no {name!r} console script beside {sys.executable}. Install the package into the "
            f"environment you are running this from: `pip install -e '.[verifier]'`."
        )
    return found


def read(path: Path) -> str:
    if not path.is_file():
        raise SourceDrift(
            f"{path.relative_to(ROOT)} does not exist, and the README quotes it. Either the "
            f"artifact moved and this script needs repointing, or it was never rendered."
        )
    return path.read_text(encoding="utf-8")


def extract(path: Path, pattern: str, *, what: str, group: int = 1) -> str:
    """Pull one value out of a source file, failing loudly if the pattern no longer matches."""
    m = re.search(pattern, read(path))
    if m is None:
        raise SourceDrift(
            f"could not find {what} in {path.relative_to(ROOT)} using /{pattern}/. The README "
            f"carries this number, so it has to come from here or not be on the page."
        )
    return m.group(group)


def rewrap(text: str, width: int = int(CAPTURE_COLUMNS)) -> str:
    """Hard-wrap over-long lines at the same column Rich wraps at, keeping each line's indent.

    The rendered grader cards were written to disk with no width limit, because a card is read in
    an editor and a remedy string broken across lines is harder to copy. On a README the same line
    scrolls off the side, so it is wrapped here rather than shortened: every word survives, and the
    only thing that changes is where the line ends. Nothing else on the page is re-flowed.
    """
    out: list[str] = []
    for line in text.splitlines():
        if len(line) <= width:
            out.append(line)
            continue
        indent = " " * (len(line) - len(line.lstrip()))
        out.extend(
            textwrap.wrap(
                line.strip(),
                width=width,
                initial_indent=indent,
                subsequent_indent=indent + "  ",
                break_long_words=False,
                break_on_hyphens=False,
            )
        )
    return "\n".join(out)


def fence(text: str, lang: str = "text") -> str:
    """Wrap captured output in a code fence.

    Not decoration. `artifacts/claims.py` masks fenced blocks before it looks for unbound numbers,
    and that is the right rule rather than a loophole: a number inside a fence is output rather
    than an assertion, and the fence is the page saying so. It is also why this script puts every
    measured decimal inside one, so README.md passes the claims gate with no baseline of its own.
    """
    return f"```{lang}\n{text.rstrip()}\n```"


# ---------------------------------------------------------------------------
# The registry
# ---------------------------------------------------------------------------


@dataclass
class Registry:
    """One snapshot of what the library knows about itself."""

    n_instruments: int
    n_wedge_instruments: int
    n_quantities: int
    n_wedge_quantities: int
    n_series: int
    reasons: tuple[tuple[str, str], ...]
    n_invariance_groups: int
    n_regime_conditions: int


def load_registry() -> Registry:
    """Read the live registry, the way `docs/gen_catalogue.py` does.

    Deliberately the loader the capability report itself uses, rather than the YAML, so a count on
    the front page and a count in the capability report cannot disagree.
    """
    from reward_lens.access.report import load_instrument_catalogue
    from reward_lens.core.envelope import RegimeCondition
    from reward_lens.core.invariance import GROUPS
    from reward_lens.core.quantity import QUANTITIES, load_quantities
    from reward_lens.core.reading import REASON_MEANING, RefusalReason

    load_quantities()
    instruments = load_instrument_catalogue()
    reasons = tuple(
        (r.name, " ".join(REASON_MEANING[r].split()))
        for r in sorted(RefusalReason, key=lambda x: x.name)
    )
    return Registry(
        n_instruments=len(instruments),
        n_wedge_instruments=sum(1 for i in instruments if i.wedge),
        n_quantities=len(QUANTITIES),
        n_wedge_quantities=sum(1 for q in QUANTITIES.values() if q.wedge),
        n_series=len({i.id[0] for i in instruments if i.id}),
        reasons=reasons,
        # `trivial` is not one of them. It is the declaration a quantity makes when it has no
        # non-trivial invariance to respect, and counting it would inflate the number. It has
        # exactly one spelling so that the count cannot depend on which one a caller used.
        n_invariance_groups=len([g for g in GROUPS if g != "trivial"]),
        n_regime_conditions=len(RegimeCondition),
    )


# ---------------------------------------------------------------------------
# Block: the capability report
# ---------------------------------------------------------------------------

#: The record is the twelve-step GRPO fixture that ships in the repository, written by a real
#: `GRPOTrainer` against real weights. A stranger cannot run the command against it without cloning
#: the repo, which is why the block below prints the invocation with a placeholder path and then
#: shows the output of the real one. The two are the same command; only the argument differs.
CAPABILITIES_ARGV = [
    "reward-lens",
    "capabilities",
    "--record",
    "tests/fixtures/grpo_run/short",
    "--grader",
    "https://my-judge.example/score",
    "--substrate",
    "NEURAL_GEN",
]

#: How many rows of each list to print before eliding. The report itself lists every one; the front
#: page shows enough to make the shape obvious and then says how many it left out, counted rather
#: than guessed. Elision is the only editorial act this file performs on captured output, and it is
#: always accompanied by the count it elided.
CAPABILITIES_AVAILABLE_SHOWN = 2
CAPABILITIES_REFUSALS_SHOWN = 2


def _split_capability_sections(text: str) -> dict[str, list[str]]:
    """Split the report into its four section headings, keeping the order they were printed in."""
    sections: dict[str, list[str]] = {}
    current = ""
    for line in text.splitlines():
        if line and not line.startswith(" "):
            current = line.split("  ")[0].strip()
            sections[current] = [line]
        elif current:
            sections[current].append(line)
    return sections


def block_capabilities() -> str:
    """The first command anyone runs, captured against the record that ships in the repository.

    The report is long by design: it lists every quantity it cannot reach and why. The front page
    shows the four resolutions in full and the first two refusals, because the point a reader needs
    in one screen is the *shape* of a refusal, not the census.
    """
    out = capture([console_script("reward-lens"), *CAPABILITIES_ARGV[1:]])
    sections = _split_capability_sections(out)
    for name in ("ACCESS RESOLVED", "REGIME MEASURED", "AVAILABLE NOW", "REFUSED, WITH REMEDY"):
        if name not in sections:
            raise SourceDrift(
                f"`reward-lens capabilities` printed no {name!r} section. The report has four "
                f"sections and the README quotes all four."
            )

    lines: list[str] = ["$ " + " ".join(CAPABILITIES_ARGV), ""]
    for name in ("ACCESS RESOLVED", "REGIME MEASURED"):
        lines.extend(ln.rstrip() for ln in sections[name] if ln.strip())
        lines.append("")

    lines.extend(_elide(sections["AVAILABLE NOW"], CAPABILITIES_AVAILABLE_SHOWN, "more available"))
    lines.append("")
    lines.extend(
        _elide(
            sections["REFUSED, WITH REMEDY"],
            CAPABILITIES_REFUSALS_SHOWN,
            "more refused, each with its own reason and its own remedy",
        )
    )
    return fence("\n".join(lines).rstrip())


#: A row in the availability or refusal list starts at column two with a quantity id. Continuation
#: lines are indented further, so the head of each entry is what this matches.
_REPORT_ROW_RE = re.compile(r"^  \S")


def _elide(section: list[str], keep: int, what: str) -> list[str]:
    """Keep the heading and the first ``keep`` entries, then say how many were dropped."""
    heads = [i for i, ln in enumerate(section[1:], start=1) if _REPORT_ROW_RE.match(ln)]
    if not heads:
        # Both lists have an empty form, "nothing. No registered estimator resolves ...", and that
        # is a real answer rather than a missing section, so it is printed as it stands.
        return [ln.rstrip() for ln in section if ln.strip()]
    end = heads[keep] if len(heads) > keep else len(section)
    out = [ln.rstrip() for ln in section[:end] if ln.strip()]
    dropped = len(heads) - min(keep, len(heads))
    if dropped:
        out.append(f"  ... {dropped} {what}")
    return out


# ---------------------------------------------------------------------------
# Block: the card plan
# ---------------------------------------------------------------------------

#: The exact source the README shows and the exact source this script runs. There is one copy of
#: it, here, so the two cannot come apart. It writes the grader it is about to measure, because a
#: front-page example that points at a file the reader does not have is not runnable, and the whole
#: claim of this file is that everything on the page ran.
CARD_PLAN_SOURCE = """\
from pathlib import Path

from reward_lens.measure.card import CardInputs, card_plan
from reward_lens.verifier import ListCorpus, Rollout, VerifierUnderTest

# Your grader. This one is four lines; SWE-bench's is four hundred.
Path("grade.py").write_text(
    "def grade(answer, gold):\\n"
    "    return 1.0 if answer.strip() == gold.strip() else 0.0\\n"
)

plan = card_plan(
    CardInputs(
        verifier=VerifierUnderTest(Path("grade.py"), entrypoint="grade"),
        corpus=ListCorpus(
            tuple(Rollout(id=f"r{i}", inputs={"answer": "4", "gold": "4"}) for i in range(20))
        ),
    )
)
print(plan.render())
"""

#: Which of the thirteen card fields the front page shows in full. One that reads, and two that
#: refuse for different reasons, which is the whole lesson in three lines.
CARD_PLAN_FIELDS_SHOWN = ("coverage", "variance components", "curl mass")


def block_card_plan_code() -> str:
    return fence(CARD_PLAN_SOURCE.rstrip(), "python")


def _card_plan_output(tmp: Path) -> str:
    script = tmp / "card_plan_example.py"
    script.write_text(CARD_PLAN_SOURCE, encoding="utf-8")
    return capture([sys.executable, str(script)], cwd=tmp)


def block_card_plan_output(tmp: Path) -> str:
    """The plan the code above actually prints, trimmed to a few of the card's fields.

    `card_plan` makes no grader call and loads no model, so this runs in about a second and is the
    cheapest honest thing the library does.
    """
    out = _card_plan_output(tmp)
    lines = out.splitlines()
    header = [ln for ln in lines[:8] if ln.strip()]
    total = int(
        re.search(r"\d+ of (\d+) fields would read", out).group(1)  # type: ignore[union-attr]
        if re.search(r"\d+ of (\d+) fields would read", out)
        else 0
    )
    if not total:
        raise SourceDrift(
            "the card plan printed no 'N of M fields would read' summary. That line is what the "
            "README counts against, so the elision below would be guessing."
        )

    keep: list[str] = []
    capturing = False
    seen: list[str] = []
    for ln in lines:
        name = ln[2:].split("  ")[0].strip() if ln.startswith("  ") and ln[2:3] != " " else ""
        if name:
            capturing = name in CARD_PLAN_FIELDS_SHOWN
            if capturing:
                seen.append(name)
        if capturing:
            keep.append(ln)
    missing = [f for f in CARD_PLAN_FIELDS_SHOWN if f not in seen]
    if missing:
        raise SourceDrift(
            f"the card plan no longer has {missing} among its fields, and the README quotes them. "
            f"Repoint CARD_PLAN_FIELDS_SHOWN at fields the card still has."
        )
    body = "\n".join(header + [""] + keep).rstrip()
    elided = total - len(CARD_PLAN_FIELDS_SHOWN)
    return fence(body + f"\n\n  ... {elided} more fields, same shape")


# ---------------------------------------------------------------------------
# Block: the grader card, on four real scoring programs
# ---------------------------------------------------------------------------

#: Rendered grader cards, one file per scoring program. `reward_lens.measure.card` writes them, and
#: this script reads them rather than re-rendering them: a render needs the four graders' source and
#: a corpus fetched from four upstream projects, which is not something a README build should do.
#: The cards are release artifacts published beside the run, not files this tree carries, so the two
#: blocks below are optional and skip themselves when the directory is absent.
CARD_RELEASE = ROOT / "artifacts" / "grader_cards"
CARD_SUBJECTS = ("is_equiv", "swebench", "verl_gsm8k", "verl_search_r1")

_CARD_TOTALS_RE = re.compile(r"^\s*(\d+) of (\d+) fields read and (\d+) refused", re.M)


def _require_cards() -> None:
    if not CARD_RELEASE.is_dir():
        raise MissingArtifact(
            f"no rendered grader cards at {CARD_RELEASE.relative_to(ROOT)}. They are published "
            f"with the run rather than carried in the source tree."
        )


def card_totals() -> tuple[int, int, int, int]:
    """Add up the four rendered cards: subjects, fields, read, refused.

    Computed from the cards themselves rather than restated, so a card that gains a field or starts
    reading one it used to refuse moves the front page with it.
    """
    _require_cards()
    n_read = n_refused = n_fields = 0
    for subject in CARD_SUBJECTS:
        text = read(CARD_RELEASE / f"{subject}.txt")
        m = _CARD_TOTALS_RE.search(text)
        if m is None:
            raise SourceDrift(
                f"the rendered card for {subject} carries no 'N of M fields read and K refused' "
                f"line. That line is what the README counts, so either the renderer changed its "
                f"summary or the card was re-rendered by something else."
            )
        n_read += int(m.group(1))
        n_fields += int(m.group(2))
        n_refused += int(m.group(3))
    if n_read + n_refused != n_fields:
        raise SourceDrift(
            f"the four cards report {n_read} read and {n_refused} refused against {n_fields} "
            f"fields, which do not add up. One of them is being parsed wrong."
        )
    return len(CARD_SUBJECTS), n_fields, n_read, n_refused


def block_card_totals() -> str:
    """One sentence, with every number in it computed from the rendered cards."""
    n_subjects, n_fields, n_read, n_refused = card_totals()
    by_reason: dict[str, int] = {}
    for subject in CARD_SUBJECTS:
        for line in read(CARD_RELEASE / f"{subject}.txt").splitlines():
            m = re.match(r"^\s+\S.*?REFUSED\s+([A-Z_]+)\s*$", line)
            if m:
                by_reason[m.group(1)] = by_reason.get(m.group(1), 0) + 1
    order = sorted(by_reason.items(), key=lambda kv: (-kv[1], kv[0]))
    tally = ", ".join(f"{n} {name}" for name, n in order)
    return fence(
        f"{n_subjects} scoring programs, {n_fields} card fields\n"
        f"  {n_read} read\n"
        f"  {n_refused} refused, and none of them for want of access:\n"
        f"      {tally}\n"
        f"\n"
        f"  rendered by `reward_lens.measure.card` and published with the run"
    )


#: The stretch of the `is_equiv` card the README quotes. Line numbers move; this is anchored on the
#: field name, which does not.
CARD_EXCERPT_FIELDS = ("surviving mutants", "exploit-family accounting")


def block_card_excerpt() -> str:
    """Two fields from a real card: one that read and said something bad, one that refused."""
    _require_cards()
    text = read(CARD_RELEASE / "is_equiv.txt")
    lines = text.splitlines()
    starts = {}
    for i, ln in enumerate(lines):
        for f in CARD_EXCERPT_FIELDS:
            if ln.startswith(f"  {f} ") or ln.strip() == f:
                starts.setdefault(f, i)
    missing = [f for f in CARD_EXCERPT_FIELDS if f not in starts]
    if missing:
        raise SourceDrift(
            f"the rendered `is_equiv` card no longer has {missing}, and the README quotes them."
        )
    out: list[str] = []
    for f in CARD_EXCERPT_FIELDS:
        i = starts[f]
        j = i + 1
        while j < len(lines) and (not lines[j].strip() or lines[j].startswith(" " * 25)):
            j += 1
        out.extend(lines[i:j])
    return fence(rewrap("\n".join(out).rstrip()))


# ---------------------------------------------------------------------------
# Block: the measured numbers
# ---------------------------------------------------------------------------
#
# Every row below is a number this build produced and every one of them is lifted out of the
# artifact that produced it. Two kinds, and the table says which is which because they are not
# equally strong:
#
#   computed  -- this script derives it at generation time from a store or a rendered artifact, so
#                the page cannot be stale by construction.
#   recorded  -- the measurement is machine-dependent (a latency, a float residual on a particular
#                dtype) so re-running it in CI would make the front page churn on every build. The
#                number is extracted from the file that recorded it, which names its own hardware,
#                and the extractor fails the build if that sentence moves.
#
# A third kind was considered and rejected: a number typed in here with a citation beside it. That
# is the thing this file exists to make impossible.

TAP_TEST = ROOT / "tests" / "acceptance" / "test_w3_1_tap.py"
CREDIT_TEST = ROOT / "tests" / "acceptance" / "test_w5_4_credit.py"
FORECAST_TEST = ROOT / "tests" / "acceptance" / "test_w4_6_forecast.py"
GRPO_FIXTURE_README = ROOT / "tests" / "fixtures" / "grpo_run" / "README.md"

#: The intransitivity campaign's evidence store, published with the run rather than carried here.
#: The rows it contributes to the table below are optional for the same reason the grader cards are:
#: absent, the table loses those rows and keeps the ones this tree can still derive.
INTRANSITIVITY_EVIDENCE = ROOT / "artifacts" / "intransitivity" / "evidence.jsonl"


def _decode(value: object) -> object:
    """Undo the evidence store's container tagging, which wraps maps and sequences."""
    if isinstance(value, dict):
        if "__map__" in value and len(value) == 1:
            return {k: _decode(v) for k, v in value["__map__"].items()}
        if "__seq__" in value and len(value) == 1:
            return [_decode(v) for v in value["__seq__"]]
        return {k: _decode(v) for k, v in value.items()}
    return value


def design_floor() -> dict[str, object]:
    """Read the campaign's design floor straight out of the evidence row that recorded it."""
    if not INTRANSITIVITY_EVIDENCE.is_file():
        raise MissingArtifact(
            f"no evidence store at {INTRANSITIVITY_EVIDENCE.relative_to(ROOT)}. It is published "
            f"with the run rather than carried in the source tree."
        )
    for line in read(INTRANSITIVITY_EVIDENCE).splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row.get("observable") == "x7.design_floor":
            return dict(_decode(row["value"]))  # type: ignore[arg-type]
    raise SourceDrift(
        "no `x7.design_floor` row in the intransitivity evidence store. The README states the "
        "campaign's own floor and it has to come from the row that computed it."
    )


def block_measured() -> str:
    tap_range = extract(
        TAP_TEST,
        r"this lands at ([\d.]+ to [\d.]+) us per",
        what="the tap's measured per-call overhead",
    )
    tap_bare = " ".join(
        extract(
            TAP_TEST,
            r"call against a bare callable of ([\d]+ to [\d]+) ns",
            what="the bare-callable baseline the tap is measured against",
        ).split()
    )
    tap_machine = extract(
        TAP_TEST,
        r"On the reference machine \(([^)]+)\)",
        what="the machine the tap overhead was measured on",
    )

    replay_groups, replay_resid = (
        extract(
            GRPO_FIXTURE_README,
            r"\|\s*`long/`\s*\|\s*(\d+)\s*\|\s*\d+\s*\|\s*([\d.e+-]+)\s*\|",
            what="the long fixture's replay residual",
            group=g,
        )
        for g in (1, 2)
    )

    credit_f64 = extract(
        CREDIT_TEST,
        r"of ([\d.e+-]+) in float32 and ([\d.e+-]+) in float64",
        what="the credit conservation residual",
        group=2,
    )
    credit_f32 = extract(
        CREDIT_TEST,
        r"of ([\d.e+-]+) in float32 and ([\d.e+-]+) in float64",
        what="the credit conservation residual",
        group=1,
    )
    credit_step = extract(
        CREDIT_TEST,
        r"sum_S g_S\| / \|sum_S g_S\| = ([\d.e+-]+)",
        what="the residual against a real optimiser step",
    )

    forecast_rows = extract(
        FORECAST_TEST,
        r"assert len\(envelopes\) == (\d+)",
        what="the number of campaign evidence rows the freeze was checked against",
    )

    # The last four rows come from run artifacts published beside the run rather than carried in
    # the source tree. If either is absent the whole block is skipped rather than rebuilt short:
    # regenerating a table of measurements minus the rows this checkout happens not to reach would
    # quietly delete real numbers from the front page, which is the opposite of what a gate is for.
    floor = design_floor()
    tally = [
        ("computed", "curl mass, campaign corpus", f"observed {floor['observed']!r}"),
        ("computed", "  lowest any grader could reach", f"floor    {floor['floor']!r}"),
        (
            "computed",
            "  registered threshold",
            f"{floor['registered_threshold']!r}, "
            f"{float(floor['threshold_as_fraction_of_floor']):.4f} of the floor",  # type: ignore[arg-type]
        ),
    ]
    _, _, n_read, n_refused = card_totals()
    card_rows = [
        (
            "computed",
            "grader card fields, four scoring programs",
            f"{n_read} read, {n_refused} refused",
        )
    ]

    rows = (
        [
            ("kind", "what was measured", "value"),
            ("----", "-----------------", "-----"),
            ("recorded", "grader wrapper, added latency per call", f"{tap_range} us"),
            ("recorded", "  against a bare callable of", f"{tap_bare} ns"),
            ("recorded", "  measured on", tap_machine),
            (
                "recorded",
                f"record replays a real trainer, {replay_groups} groups",
                f"max abs difference {replay_resid}",
            ),
            ("recorded", "credit conservation, float64", credit_f64),
            ("recorded", "  float32", credit_f32),
            ("recorded", "  against a real torch.optim.SGD step", credit_step),
            (
                "computed",
                "forecast barrier, campaign rows predating the freeze",
                f"0 of {forecast_rows}",
            ),
        ]
        + card_rows
        + tally
    )

    kw = max(len(r[0]) for r in rows)
    ww = max(len(r[1]) for r in rows)
    body = "\n".join(f"{k:<{kw}}  {w:<{ww}}  {v}" for k, w, v in rows)
    return fence(body)


# ---------------------------------------------------------------------------
# Block: the catalogue, and the refusal reasons
# ---------------------------------------------------------------------------


def block_catalogue(reg: Registry) -> str:
    return fence(
        f"{reg.n_instruments} instruments across {reg.n_series} series, "
        f"{reg.n_wedge_instruments} of them in the wedge\n"
        f"{reg.n_quantities} quantities, {reg.n_wedge_quantities} of them in the wedge\n"
        f"{reg.n_regime_conditions} regime conditions, {reg.n_invariance_groups} invariance "
        f"groups, {len(reg.reasons)} refusal reasons\n"
        f"\n"
        f"the wedge is what a record and a callable grader reach: no weights, no gradients,\n"
        f"no GPU. `reward-lens capabilities` is how you find out which of them your run is in."
    )


def block_refusal_reasons(reg: Registry) -> str:
    lines = []
    for name, meaning in reg.reasons:
        lines.append(f"{name}")
        lines.extend("    " + ln for ln in textwrap.wrap(meaning, width=84))
    return fence("\n".join(lines))


# ---------------------------------------------------------------------------
# Assembling the page
# ---------------------------------------------------------------------------


def build_blocks(tmp: Path) -> tuple[dict[str, str], dict[str, str]]:
    """Every generated block on the page, keyed by its marker name.

    Returns the blocks that were built and, beside them, the ones that were skipped because their
    source artifact is not in this checkout, each with the reason. A skipped block is not an empty
    block: the caller leaves the README's existing text in place for it.
    """
    reg = load_registry()
    builders: dict[str, Callable[[], str]] = {
        "card-plan-code": block_card_plan_code,
        "card-plan-output": lambda: block_card_plan_output(tmp),
        "catalogue": lambda: block_catalogue(reg),
        "refusal-reasons": lambda: block_refusal_reasons(reg),
    }
    blocks: dict[str, str] = {}
    skipped: dict[str, str] = {}
    for name, build in builders.items():
        try:
            blocks[name] = build()
        except MissingArtifact as exc:
            skipped[name] = str(exc)
            print(f"skipping block {name!r}: {exc}", file=sys.stderr)
    return blocks, skipped


def markers_in(text: str) -> list[str]:
    return [m.group("name") for m in _MARKER_RE.finditer(text)]


def splice(text: str, blocks: dict[str, str], skipped: dict[str, str] | None = None) -> str:
    """Replace the body of every marked region, leaving the prose around it alone.

    A marker named in ``skipped`` is passed through untouched, body and all. Its generator ran and
    said it had nothing to read; overwriting a measured block with silence because a release tree
    does not carry the run output would be worse than leaving the measurement where it is.
    """
    skipped = skipped or {}
    present = markers_in(text)
    unknown = sorted(set(present) - set(blocks) - set(skipped))
    if unknown:
        raise ReadmeDrift(
            f"README.md marks blocks this script does not build: {unknown}. Either add a generator "
            f"or delete the markers; a marker with no generator is a block that will go stale."
        )
    unused = sorted(set(blocks) - set(present))
    if unused:
        raise ReadmeDrift(
            f"this script builds blocks the README does not mark: {unused}. A generated block "
            f"nobody shows is dead weight, and a generator that silently produces nothing is how a "
            f"generator stops being a gate."
        )

    def sub(m: re.Match[str]) -> str:
        name = m.group("name")
        if name in skipped:
            return m.group(0)
        return m.group("open") + blocks[name].rstrip() + "\n" + m.group("close")

    return _MARKER_RE.sub(sub, text)


def diff(current: str, regenerated: str) -> str:
    return "".join(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            regenerated.splitlines(keepends=True),
            fromfile="README.md (on disk)",
            tofile="README.md (regenerated)",
            n=2,
        )
    )


def _skip_note(skipped: dict[str, str]) -> str:
    if not skipped:
        return ""
    return f", {len(skipped)} skipped for want of an artifact ({', '.join(sorted(skipped))})"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="gen_readme", description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="regenerate into memory and fail if the README on disk differs. What CI runs.",
    )
    mode.add_argument("--write", action="store_true", help="regenerate the blocks in place.")
    mode.add_argument("--list", action="store_true", help="list the blocks and their sizes.")
    parser.add_argument("--print", metavar="NAME", help="print one block and exit.")
    args = parser.parse_args(argv)

    import tempfile

    with tempfile.TemporaryDirectory(prefix="rl-readme-") as td:
        try:
            blocks, skipped = build_blocks(Path(td))
        except SourceDrift as exc:
            print(f"README generation failed: {exc}", file=sys.stderr)
            return 2

    if args.print:
        if args.print in skipped:
            print(f"block {args.print!r} was skipped: {skipped[args.print]}", file=sys.stderr)
            return 0
        if args.print not in blocks:
            print(f"no block named {args.print!r}. Have: {sorted(blocks)}", file=sys.stderr)
            return 2
        print(blocks[args.print])
        return 0

    if args.list:
        for name in sorted(blocks | skipped):
            if name in skipped:
                print(f"{name:<20} {'skipped':>10}  {skipped[name]}")
            else:
                print(f"{name:<20} {len(blocks[name].splitlines()):>4} lines")
        return 0

    current = read(README)
    try:
        regenerated = splice(current, blocks, skipped)
    except ReadmeDrift as exc:
        print(f"README generation failed: {exc}", file=sys.stderr)
        return 2

    if args.write:
        if regenerated == current:
            print("README.md is already current.")
            return 0
        README.write_text(regenerated, encoding="utf-8")
        print(f"README.md rewritten: {len(blocks)} generated blocks{_skip_note(skipped)}.")
        return 0

    # --check, and the default, are the same thing: the gate. A skipped block is not drift, so it
    # is reported and passed over rather than counted against the page.
    if regenerated == current:
        print(
            f"README.md is current: {len(blocks)} generated blocks all match{_skip_note(skipped)}."
        )
        return 0
    print(
        "README.md has drifted from the code it describes. Every example on the front page is "
        "generated, so this is not a formatting complaint: something the page shows has changed "
        "and the page did not. Run `python scripts/gen_readme.py --write` and read the diff "
        "before committing it.\n",
        file=sys.stderr,
    )
    print(diff(current, regenerated), file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
